services:
  app:
    build: app
    ports:
      - 8501:8501
    volumes:
      - c:\dbfs\ChromaDB:/dbfs/ChromaDB
    networks:
      - net
  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - vol:/ollama
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
networks:
  net:
    driver: bridge

volumes:
  vol:
    driver: local

